export const TYPES = {
	ICampaignsRepository: Symbol.for("ICampaignsRepository"),
	IUsersRepository: Symbol.for("IUsersRepository"),
	IDonorsRepository: Symbol.for("IDonorsRepository"),
	IConfirmationsRepository: Symbol.for("IConfirmationsRepository"),
	IMetricsRepository: Symbol.for("IMetricsRepository"),
	IBloodBankRepository: Symbol.for("IBloodBankRepository"),

	GetCampaignsUseCase: Symbol.for("GetCampaignsUseCase"),
	GetCampaignsSummaryUseCase: Symbol.for("GetCampaignsSummaryUseCase"),
	CreateCampaignUseCase: Symbol.for("CreateCampaignUseCase"),
	SendCampaignEmailUseCase: Symbol.for("SendCampaignEmailUseCase"),
	CloseCampaignUseCase: Symbol.for("CloseCampaignUseCase"),
	SignInUseCase: Symbol.for("SignInUseCase"),
	GetProfileUseCase: Symbol.for("GetProfileUseCase"),
	ConfirmDonationIntentionUseCase: Symbol.for(
		"ConfirmDonationIntentionUseCase",
	),
	GetMetricsUseCase: Symbol.for("GetMetricsUseCase"),
	GetDailyMetricsUseCase: Symbol.for("GetDailyMetricsUseCase"),
	GetBloodBankSummaryUseCase: Symbol.for("GetBloodBankSummaryUseCase"),
	GetDonorsUseCase: Symbol.for("GetDonorsUseCase"),
	CountEligibleDonorsUseCase: Symbol.for("CountEligibleDonorsUseCase"),

	GetCampaignsController: Symbol.for("GetCampaignsController"),
	GetCampaignsSummaryController: Symbol.for("GetCampaignsSummaryController"),
	CreateCampaignController: Symbol.for("CreateCampaignController"),
	SignInController: Symbol.for("SignInController"),
	SignOutController: Symbol.for("SignOutController"),
	GetProfileController: Symbol.for("GetProfileController"),
	ConfirmDonationIntentionController: Symbol.for(
		"ConfirmDonationIntentionController",
	),
	GetMetricsController: Symbol.for("GetMetricsController"),
	GetDailyMetricsController: Symbol.for("GetDailyMetricsController"),
	GetBloodBankSummaryController: Symbol.for("GetBloodBankSummaryController"),
	GetDonorsController: Symbol.for("GetDonorsController"),
	CountEligibleDonorsController: Symbol.for("CountEligibleDonorsController"),

	IPasswordHasher: Symbol.for("IPasswordHasher"),
	IEmailService: Symbol.for("IEmailService"),
	IEmailTemplateRenderer: Symbol.for("IEmailTemplateRenderer"),
	IJobQueue: Symbol.for("IJobQueue"),
}
